### ISSUE TITLE
Add Bison TRISO examples

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/virtual_test_bed#100]
We will add Bison TRISO examples and documents.

**Comment by jiangwen84** [comment]
@GiudGiud which folder should I add the Bison inputs?  Or create a new folder? thanks.

**Comment by GiudGiud** [comment]
Are they more like HTGR or PBFHR trisos? The users can find them in either folder, but it would allow us to keep the classification by reactor.

**Comment by GiudGiud** [comment]
Closing as addressed by #103
