### ISSUE TITLE
VTR Core Model

### ISSUE THREAD

**Issue by folkthom** [idaholab/virtual_test_bed#111]
Import an INL VTR core model to the VTB. See https://www.sciencedirect.com/science/article/pii/S0306454922001013. 

The model is multi-physics with Griffin, Bison, and SAM inputs.

- [x] Update and improve model syntax.
- [x] Generate VTB documentation.
- [x] Create regression tests.

PR #112

**Comment by GiudGiud** [comment]
Closing as addressed by #112
