### ISSUE TITLE
SAM generic PB-HTGR model

### ISSUE THREAD

**Issue by zhieejhia93** [idaholab/virtual_test_bed#129]
The goal is to use SAM to model a generic Pebble-Bed High Temperature Gas-Cooled Reactor (PB-HTGR):

- The model will primarily utilize SAM's PbCoreChannel component to model the pebble bed core of the reactor. This will enable the model to capture the thermal hydraulics behavior of the core in both axial and radial directions. 
- A steady-state and a transient simulations will be provided as demonstrations.

**Comment by GiudGiud** [comment]
Closing as addressed by #130
