### ISSUE TITLE
Adding a Griffin DFEM-SN CMFD standalone model for a 3D heterogeneous single assembly problem of a lead-cooled fast reactor

### ISSUE THREAD

**Issue by pak1sol** [idaholab/virtual_test_bed#151]
This issue is to start a pull request for a Griffin DFEM-SN CMFD standalone model for a 3D heterogeneous single assembly problem of a lead-cooled fast reactor to be merged into VTB.

**Comment by GiudGiud** [comment]
sounds good. Let's have a new folder : lfr for this reactor type

**Comment by pak1sol** [comment]
> sounds good. Let's have a new folder : lfr for this reactor type

Yes, I will make a separate folder for this. Please note that I've changed the model: Griffin-MOOSE heat conduction to Griffin standalone. Let me do this at this time and add multiphysics model later on.

**Comment by pak1sol** [comment]
@GiudGiud I have a question. I generated XS using MC2-3/twodant which I think is noteworthy to discuss in this VTB model since axial leakage is taken into account in heterogeneous 2D assembly calculation. This is not quite common practice actually so that's why it would be somewhat beneficial to discuss. However, this whole procedure is not fully available in Griffin yet, so can I just put MC2-3 input here to pin point what's important in preparing XS for this model as just an information even though the MC2-3 input will not be run here?

**Comment by pak1sol** [comment]
Got it. Thanks for the confirmation.

**Comment by GiudGiud** [comment]
Closed by #169
