### ISSUE TITLE
Adding Dynamic Multiphysics simulation of RIA in the GCMR Assembly 

### ISSUE THREAD

**Issue by aabdelhameedd** [idaholab/virtual_test_bed#231]
Adding a new simulation in the Gas-cooled Microreactor (GCMR) assembly of a postulated reactivity insertion accident (RIA). Similarly, to the previous simulation of flow blockage, a 3-D dynamic Multiphysics simulation was completed by coupling Griffin, BISON, SAM, where the Griffin transport solver DFEM-SN with CMFD acceleration was used.

**Comment by GiudGiud** [comment]
Closing as addressed by #230
