### ISSUE TITLE
Create BISON 2D and 3D TRISO examples

### ISSUE THREAD

**Issue by jiangwen84** [idaholab/virtual_test_bed#236]
We had 1D BISON TRISO examples in VTB repo. It is better to add a few 2D and 3D examples.

**Comment by GiudGiud** [comment]
@jiangwen84 any update on this?

**Comment by mtnwalker** [comment]
Hey Guillaume - I have this PR and will push it shortly.

**Comment by jiangwen84** [comment]
@mtnwalker did you ever push it? Please let me know if you need any help.

**Comment by jiangwen84** [comment]
@mtnwalker no push. I just wanted to know what you already have on your PR. I might need to add something else, depending on what you have done so far. thanks!
