### ISSUE TITLE
HTTR Core multiphysics RELAP-7/Griffin/BISON model

### ISSUE THREAD

**Issue by kyleeswanson** [idaholab/virtual_test_bed#240]
A steady state multiphysics core model was developed by the analysis team here at INL. 
We wish to contribute this model to the virtual test bed

it includes
- HTTR documentation
- Griffin homogenized core model
- Bison homogenized core conduction model
- BISON heterogeneous pin model
- RELAP-7 channel models for pins and control rod channels

**Comment by GiudGiud** [comment]
Let's use a single issue for the entire model, and keep it more detailed.
However please do not populate this with any model information until this has cleared the lab review process
