### ISSUE TITLE
VTR Griffin input missing `equivalence_grid_variables` parameter

### ISSUE THREAD

**Issue by shikhar413** [idaholab/virtual_test_bed#245]
There is a mistake with the VTR Griffin input, where `equivalence_grid_variables` in not explicitly defined in `sfr/vtr/griffin_multiphysics.i`. This shouldn’t affect the test suite results since the SPH factors are all set to 1 in this example. However, if a user was to use this input file as a starting point with correct SPH factor values they would not get the intended result, since by default if the `equvalence_grid_variables` parameter is not provided Griffin will assume SPH factors at a fixed gridapoint (instead of interpolating based on the value of the grid variables). This can be easily fixed by explicitly setting the `equivalence_grid_variables` parameter.

**Comment by GiudGiud** [comment]
Closing as addressed by #246
