### ISSUE TITLE
Hydride-Moderated Heat-Pipe-cooled Microreactor with Hydrogen Redistribution Response

### ISSUE THREAD

**Issue by sallustius** [idaholab/virtual_test_bed#308]
## Model Description

A microreactor model including hydrogen redistribution in yttrium hydride and the associated neutronic feedback. The model is based on the Simplified Microreactor Benchmark Assessment (SiMBA) problem described in an article published on Annals on Nuclear Energy. This is a 3D model including neutron transport (DFEM-SN), heat transfer, heat pipe model, and hydrogen redistribution. The model needs to be run on HPC. It uses Griffin for neutronics, Bison for modeling hydrogen redistribution and solid heat transfer, and Sockeye for the heat pipes. The model computes the asymptotic value for power, temperature, and H/Y stoichiometric ratio in the reactor.

## Project description

The model creation was funded by a Laboratory-Directed Research and Development (LDRD) project at Idaho National Laboratory (INL) led by @sallustius. The model was developed @sallustius and @vincentlaboure at INL.

## Impact
Four characteristics distinguish this model from current VTB microreactors models:
- The neutronics analysis considers the impact of hydrogen redistribution within the yttrium hydride pins. This is achieved by incorporating hydrogen redistribution modeling into Bison and by parameterizing the multigroup macroscopic cross sections based on the stoichiometric ratio.
- The coupling between neutronics and solid heat conduction, including the 101 heat pipe sub-applications, is achieved through a fixed-point iteration approach. This logic relies on the effective multiplication factor's residual error reduction, deviating from the default coupling method performed at each Richardson iteration. This logics allows to minimize the number of iterations between neutron transport and the other physics, and, therefore, the execution time of the simulation.
- The heat pipe is modeled using the Vapor-Only Flow Model (VOFM) in Sockeye. This heat pipe model couples "a 1D single-phase, compressible flow formulation for the vapor phase in the core region to 2D heat conduction in the wick and annulus". The VOFM allows to obtain better accuracy with respect to the Conduction Heat Pipe Model (CHPM), based on thermal resistance, while being numerically more stable than the two-phase Flow-Model.
- Special care is taken to obtain excellent mass and energy conservation across the multiphysics model, without relying on mesh refinement. The total hydrogen mass was conserved within 4e-5\% and the total global energy discrepancy is below 0.04\%.

**Comment by GiudGiud** [comment]
Closing as completed by #317
