### ISSUE TITLE
GCMR missing certain dimensions on Model Description Page

### ISSUE THREAD

**Issue by lewisgross1296** [idaholab/virtual_test_bed#309]
## Description
I am working on modeling the VTB GCMR, and I noticed the model [description](https://mooseframework.inl.gov/virtual_test_bed/microreactors/gcmr/GCMR_Assembly_Model_Description.html) was missing information about the moderator compact radius and thickness of the FeCrAl envelope. I was able to get it after doing some investigating, but I believe these details should be added to the linked page. This isn't exactly a "bug" but bug report was the closest option in the issue templates.

## Impact
This slows down others who would want to model this system, as they'd have to do some digging when it would be fairly easy to add these details to the page.

## Further on
Another small nitpick would be that it would be useful to provide more info about the TRISO and B4C particles on this page, but that one is more up for debate if it is worth including. Could argue people should choose from the literature for their model, though I'd argue having a centralized list of radii/materials is better for cross-code comparison.

**Comment by GiudGiud** [comment]
I m all in favor of more documentation. Can you add those or do we need to contact the original authors of the model to help here?

**Comment by lewisgross1296** [comment]
The YH2 moderator radius I'm using is 0.95 cm. The FeCrAl envelope thickness is 0.05 cm. I reached out to @nstauff for these, so it would be good for him to confirm. For the TRISO particles, I'm using these radii for each spherical shell region
```
r_fuel_kernel = 212.5e-4 # cm
r_Buffer = 312.5e-4 # cm
r_PyC1_inner = 352.5e-4 # cm
r_SiC = 387.5e-4 # cm
r_PyC2_outer = 427.5e-4 # cm
```
For the poison particles, I'm using these radii
```
r_B4C_kernel = 0.0100 # cm (100 microns of B4C)
r_poison_buff = 0.0118 # cm (118 microns of graphite buffer)
r_poison_PyC1_outer = 0.0141 # cm (123 microns of PyC1)
```

**Comment by nstauff** [comment]
@lewisgross1296 - thanks for proposing some improvement to the documentation.
Some clarification:
- outer radius of YH2 is 0.843 cm
- there is a Cr coating of 0.007cm on the inner cladding region
- FeCrAl cladding thickness is 0.05 cm
- outer radius of moderator pin is 0.900 cm

**Comment by lewisgross1296** [comment]
Wanted to double check, but the Cr coating is natural Chromium (see attached abundances)? I'm using a density of 7.15 g/cm^3 (what I could find on Wikipedia), though that is at room temperature.

<img width="337" alt="natural_Cr" src="https://github.com/idaholab/virtual_test_bed/assets/43077972/abb72f00-be8d-4ec7-ac62-b0cf753a9685">

**Comment by nstauff** [comment]
Thanks - I am using Cr density of 7.19g/cc
The abundance of Cr isotopes are correct.
