### ISSUE TITLE
3D Steady-state Lotus Molten Chloride Reactor Model.

### ISSUE THREAD

**Issue by mtnwalker** [idaholab/virtual_test_bed#313]
## Model Description
This model is a multiphysics 3D model of the Lotus Molten Chloride Reactor (LMCR) using only Griffin and Pronghorn. Must be run on HPC.

## Project description
This model was developed by Mauricio Tano & Rodrigo de Oliveira. Funded by the NEAMS  MSR App Driver program. 

## Impact
This is a valuable contribution to modeling the Lotus MCR with 3D resolution which will be used by the NEAMS program for further modeling development and transient analyses in FY24.

**Comment by GiudGiud** [comment]
Closing as completed by #331
