### ISSUE TITLE
Molten Salt Fast Reactor Thermochemistry Model

### ISSUE THREAD

**Issue by mtnwalker** [idaholab/virtual_test_bed#315]
## Model Description
This model is a multiphysics RZ model of the Molten Salt Fast Reactor that solves the steady-state thermochemistry of the system using a multiphysics restart currently on VTB.  Can be run on workstation.

## Project description
This model was developed by Samuel Walker and was funded by the NEAMS program and ART-MSR program.

## Impact
This is a valuable contribution to modeling the full multiphysics behavior of Molten Salt Reactors by including the important aspect of thermochemistry. Gives an example of how to use the newly MOOSE wrapped Thermochimica within the chemical reactions module.

**Comment by GiudGiud** [comment]
Closing as completed by #316
