### ISSUE TITLE
Regold of Bison TRISO examples due to typo correction in Bison

### ISSUE THREAD

**Issue by gambka** [idaholab/virtual_test_bed#357]
## Reason

The examples `virtual_test_bed/htgr/triso_fuel` and `microreactors/mrad/triso_failure` currently fail on Bison testing due to a recent typo correction in the correlation of the `PyCCharacteristicStrength` model used in one of the TRISO layers.

## Design

No change in model inputs, simply a modification in the results. Requires a regold.

## Impact

Up to date results for TRISO examples.

**Comment by GiudGiud** [comment]
Needs a submodule update too most likely
