### ISSUE TITLE
Adding Mastodon Ex. 14 to VTB - 'Seismic Analysis'

### ISSUE THREAD

**Issue by kyleeswanson** [idaholab/virtual_test_bed#402]
## Model Description
Adding Mastodon Ex. 14 to the VTB under the name 'seismic analysis'; uses Mastodon.

## Project description
Team consists of intern Kylee Swanson and mentor Guillaume Guidicelli, funded by VTB.

## Impact
Allows for seismic activity analysis of nuclear reactor models.

**Comment by GiudGiud** [comment]
Closing as resolved by #396
