### ISSUE TITLE
rz_meshgenerator parameter no longer needed in ABTR SFR workflow example

### ISSUE THREAD

**Issue by shikhar413** [idaholab/virtual_test_bed#432]
## Reason

Making some updates to Griffin where `MCC3CrossSection/rz_meshgenerator` will be removed outright. This parameter is defined in the ABTR workflow but doesn't currently affect the code so it can be removed.

## Design

Removal of parameter

## Impact

No impact, makes it so that the parameter can be removed from Griffin without any VTB test failures. For more info, please see https://github.inl.gov/ncrc/griffin/pull/2115 and https://civet.inl.gov/job/2464417/

**Comment by GiudGiud** [comment]
Closing as resolved by #431
