### ISSUE TITLE
Regold TRISO test to accommodate UCO FGR BISON model modifications

### ISSUE THREAD

**Issue by hirsja** [idaholab/virtual_test_bed#445]
## Reason
Modifications to the UCO FGR model in BISON require regolding a TRISO test (`triso_1d_bison`).

## Design
Regold TRISO test.

## Impact
Regold TRISO test.

**Comment by elementx54** [comment]
@hirsja Did you forget to open the PR? I see the commit, but I don't see the PR into VTB.
