### ISSUE TITLE
Correct tags for the divertor monoblock model

### ISSUE THREAD

**Issue by licharlot** [idaholab/virtual_test_bed#471]
## Reason

The tags are incorrect or not defined

## Design

- Change name tag  from "SAM Generic PBR Model" to "Divertor Monoblock"
- Add image tag
- Add description tag
## Impact

Improved rendering of the model in the search engine

**Comment by GiudGiud** [comment]
this is fixed already,just need the website to update

**Comment by licharlot** [comment]
Ok I missed that. Thanks!
